@baseUrl = http://localhost:4000

###
GET {{baseUrl}}/usuario/eu
Content-Type: application/json
x-access-token: SEU_TOKEN_AQUI

###
POST {{baseUrl}}/usuario/login
Content-Type: application/json

{
    "email": "admin@email.com",
    "senha": "123456"
}

###
POST {{baseUrl}}/usuario/novo
Content-Type: application/json

{
    "nome": "Admin",
    "email": "admin@email.com",
    "senha": "123456",
    "tipo": "administrador"
}

###
POST {{baseUrl}}/usuario/refresh-token
Content-Type: application/json

{
    "refreshToken": "SEU_REFRESH_TOKEN_AQUI"
}
